---
title: "Schedule"
format: 
  html:
    code-fold: false
    code-tools: false
editor: visual
---

::: {.callout-note appearance="minimal"}
## Day 1: 15th January 2024
:::

+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| Time          | Topic                                                                                                                                                                                      | Type      | Presenter                                                                             |
+===============+============================================================================================================================================================================================+===========+=======================================================================================+
| 08:30 - 09:30 | [Definition and purpose of systematic reviews](https://docs.google.com/presentation/d/1-N3FvzShffZwHEUSO8rnA0nBr2kz0dLr/edit?usp=share_link&ouid=113648051799093918679&rtpof=true&sd=true) | Lecture   | [Muema Mulei](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema)     |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| 09:30 - 10:30 | [Research question formulation for a systematic review](https://drive.google.com/drive/folders/1CdOdnsk9ntF1hBlm8WLBPM2gvI6DBUb7?usp=share_link)                                           | Lecture   | [George Paul Omondi](https://globalhealthcenter.umn.edu/staff/george-omondi-paul)     |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| 10:30 - 11:00 | ☕ Tea break                                                                                                                                                                               |           |                                                                                       |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| 11:00 - 12:00 | Research question formulation for a systematic review                                                                                                                                      | Practical | [George Paul Omondi](https://globalhealthcenter.umn.edu/staff/george-omondi-paul)     |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| 12:00 - 13:00 | [Study selection criteria (Inclusion and exclusion criteria) and grey literature](https://drive.google.com/file/d/1S3rKyQDk8odwAN1ImQ-vQUYx46zv5ExQ/view?usp=share_link)                   | Lecture   | [George Paul Omondi](https://globalhealthcenter.umn.edu/staff/george-omondi-paul)     |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| 13:00 - 14:00 | 🍲 Lunch break                                                                                                                                                                             |           |                                                                                       |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| 14:00 - 15:00 | Inclusion and exclusion criteria                                                                                                                                                           | Practical | [George Paul Omondi](https://globalhealthcenter.umn.edu/staff/george-omondi-paul)     |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| 15:00 - 16:00 | [Literature search strategies](https://drive.google.com/file/d/12VPFZOzrHz8hVZtIFHcp2YT0NlaNyR2e/view?usp=share_link)                                                                      | Lecture   | [Victor Riitho](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-victor-riitho) |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| 16:00 - 16:30 | ☕ Tea break                                                                                                                                                                               |           |                                                                                       |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| 16:30 - 17:00 | Develop a search strategy                                                                                                                                                                  | Practical | [Victor Riitho](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-victor-riitho) |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------------------------------------------------------------------------------------+

::: {.callout-note appearance="minimal"}
## Day 2: 16th January 2024
:::

+---------------+---------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| Time          | Topic                                                                                                                                 | Type                   | Presenter                                                                             |
+===============+=======================================================================================================================================+========================+=======================================================================================+
| Before 8:30   | [Day 1 evaluation](https://forms.gle/DcfTaBpKQo6C4vqw8)                                                                               |                        |                                                                                       |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 08:30 - 09:30 | Feedback session on the search strategies (Presentations)                                                                             | Discussion             | All                                                                                   |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 09:30 - 10:30 | Conduct searches on different databases                                                                                               | Practical              | [Victor Riitho](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-victor-riitho) |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 10:30 - 11:00 | ☕ Tea break                                                                                                                          |                        |                                                                                       |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 11:00 - 13:00 | How to use software to remove duplicates (QC Rayyan)                                                                                  | Practical              | [Mutono Nyamai](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mutono-nyamai) |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 13:00 - 14:00 | 🍲 Lunch break                                                                                                                        |                        |                                                                                       |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 14:00 - 15:30 | [Data extraction process and tool development](https://drive.google.com/file/d/1yn7dpZRUZ38cFO6UXnHP2KvPUUNh5sBX/view?usp=share_link) | Lecture plus practical | [Victor Riitho](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-victor-riitho) |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 15:30 - 16:00 | ☕ Tea break                                                                                                                          |                        |                                                                                       |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 16:00 - 17:00 | [Quality assessment](https://drive.google.com/file/d/1PPektq1-hDFk23x8MDuqUf3SC9V93eG0/view?usp=share_link)                           | Lecture                | [Muema Mulei](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema)     |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+

::: {.callout-note appearance="minimal"}
## Day 3: 17th January 2024
:::

+---------------+--------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| Time          | Topic                                                                                                                    | Type                   | Presenter                                                                             |
+===============+==========================================================================================================================+========================+=======================================================================================+
| Before 8:30   | [Day 2 evaluation](https://forms.gle/m6LDfHZ3tRBtctyA7)                                                                  |                        |                                                                                       |
+---------------+--------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 08:30 - 09:30 | [Protocol development](https://drive.google.com/drive/folders/1XVwhMmaR629UUVUjX2E8IQpQqTFjKMVr?usp=share_link)          | Lecture                | [George Paul Omondi](https://globalhealthcenter.umn.edu/staff/george-omondi-paul)     |
+---------------+--------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 09:30 - 10:30 | Protocol development                                                                                                     | Practical              | [George Paul Omondi](https://globalhealthcenter.umn.edu/staff/george-omondi-paul)     |
+---------------+--------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 10:30 - 11:00 | ☕ Tea break                                                                                                             |                        |                                                                                       |
+---------------+--------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 11:00 - 12:30 | [Protocol registration process](https://drive.google.com/drive/folders/13Os3PZIvn1kdOMbeA0ofHQEd_8J7CJ2a?usp=share_link) | Lecture plus practical | [Muema Mulei](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema)     |
+---------------+--------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 12:30 - 13:00 | The abstract screening process                                                                                           | Practical              | [Victor Riitho](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-victor-riitho) |
+---------------+--------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 13:00 - 14:00 | 🍲 Lunch break                                                                                                           |                        |                                                                                       |
+---------------+--------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 14:00 - 15:30 | The abstract screening process                                                                                           | Practical              | [Victor Riitho](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-victor-riitho) |
+---------------+--------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 15:30 - 16:00 | ☕ Tea break                                                                                                             |                        |                                                                                       |
+---------------+--------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 16:00 - 17:00 | Data extraction process from included abstracts                                                                          | Practical              | [Victor Riitho](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-victor-riitho) |
+---------------+--------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+

::: {.callout-note appearance="minimal"}
## Day 4: 18th January 2024
:::

+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| Time          | Topic                                                                                                                                                                          | Type                   | Presenter                                                                             |
+===============+================================================================================================================================================================================+========================+=======================================================================================+
| 08:30 - 09:30 | Reporting guidelines (PRISMA)                                                                                                                                                  | Lecture                | [Muema Mulei](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema)     |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 09:30 - 10:30 | Develop a PRISMA flow chart                                                                                                                                                    | Practical              | [Muema Mulei](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema)     |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 10:30 - 11:00 | ☕ Tea break                                                                                                                                                                   |                        |                                                                                       |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 11:00 - 13:00 | [Data synthesis (geographical summary of study areas)](https://www.dropbox.com/scl/fi/a1ds1x4hefr61knadseo3/screened_abstracts_oncho.csv?rlkey=1etbntloi5rksw1z4aoohidud&dl=0) | Lecture plus practical | [Mutono Nyamai](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mutono-nyamai) |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 13:00 - 14:00 | 🍲 Lunch break                                                                                                                                                                 |                        |                                                                                       |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 14:00 - 15:30 | Data synthesis (summarising study characteristics)                                                                                                                             | Practical              | [Mutono Nyamai](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mutono-nyamai) |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 15:30 - 16:00 | ☕ Tea break                                                                                                                                                                   |                        |                                                                                       |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+
| 16:00 - 17:00 | Subgroup Analysis                                                                                                                                                              | Practical              | [Mutono Nyamai](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mutono-nyamai) |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------------------------------------------------------------------------------------+

::: {.callout-note appearance="minimal"}
## Day 5: 19th January 2024
:::

+---------------+--------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| Time          | Topic                                            | Type      | Presenter                                                                             |
+===============+==================================================+===========+=======================================================================================+
| 08:30 - 09:30 | Publication Bias Assessment                      | Practical | [Mutono Nyamai](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mutono-nyamai) |
+---------------+--------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| 09:30 - 10:30 | Assessing heterogeneity                          | Practical | [Mutono Nyamai](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mutono-nyamai) |
+---------------+--------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| 10:30 - 11:00 | ☕ Tea break                                     |           |                                                                                       |
+---------------+--------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| 11:00 - 13:00 | Meta-analysis (forest plots + regression models) | Practical | [Mutono Nyamai](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mutono-nyamai) |
+---------------+--------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| 13:00 - 14:00 | 🍲 Lunch break                                   |           |                                                                                       |
+---------------+--------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| 14:00 - 15:00 | Interpreting and reporting results               | Lecture   | [Muema Mulei](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema)     |
+---------------+--------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| 15:00 -       | Authorship and acknowledgments                   | Lecture   | [George Paul Omondi](https://globalhealthcenter.umn.edu/staff/george-omondi-paul)     |
|               |                                                  |           |                                                                                       |
| 15:30         |                                                  |           |                                                                                       |
+---------------+--------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| 15:30 - 16:00 | ☕ Tea break                                     |           |                                                                                       |
+---------------+--------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
| 16:00 - 17:00 | Discussion session / consultation                |           | All                                                                                   |
+---------------+--------------------------------------------------+-----------+---------------------------------------------------------------------------------------+
